# Copyright 2018 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

baseURL = "https://www.potercoin.ink/"
enableRobotsTXT = true
title = "Poter"

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
author = "author"
category = "categories"
tag = "tags"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = []

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories", "Authors"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories", "authors"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# First one is picked as the Twitter card image if not set on page.
#images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/blog/:slug/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true

# Image processing configuration.
[imaging]
anchor = "smart"
quality = 75
resampleFilter = "CatmullRom"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = ""

# Language configuration

[languages]
[languages.en]
description = "Poter is a powerful downloader that supports protocols such as HTTP, FTP, BitTorrent, and IPFS. Its flexible token economy empowers data value and supports data transactions including NFTs. The forum and reward board enable users to exchange information efficiently and effectively."
languageName = "English"
title = "Poter"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]
copyright = "Copyright © 2023 Poter Tech"
github_repo = "https://github.com/potercoin/potercoin"
github_project_repo = "https://github.com/potercoin/potercoin"
privacy_policy = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "c632b781ffe71b197"
algolia_docsearch = true

# current release branch - could be rc
release_branch = "main"
# the main version. Never is rc.
release_version = "v0.0.1"

slackurl = "/slack"

installurl = '/docs/installation/'
learnmoreurl = '/docs/installation/'
twitterurl = 'https://twitter.com/potercoin'

notoc = true

# First one is picked as the Twitter card image if not set on page.
images = ["images/whats-new-bg-3.jpg"]

[params.social]
github = 'potercoin'
slackurl = "/slack"
twitter = 'potercoin'

[[params.whatsnew]]
badge = 'POTER DZONE REFCARD'
body = 'The new version of Poter supports multiple resource downloads and has launched the Tieba function, making it easier for users to communicate and share resources on the platform.'
heading = 'New! Download the Install Poter'
[params.whatsnew.button]
hero_class = 'mid'
text = 'Download Now!'
url = '/documents/poter_cn.pdf'

[[params.whatsnew]]
badge = 'DOCS'
body = 'Because aria2 can handle multiple downloads at once, it encounters lots of errors in a session. aria2 returns the following exit status based on the last error encountered.'
heading = 'Poter Error Code'
[params.whatsnew.button]
hero_class = 'mid-2'
text = 'Read More'
url = '/docs/reference/error/'

[[params.whatsnew]]
badge = 'BLOG'
body = 'The Poter project has issued its own token on the FEGtoken platform, with a total issuance of 4 billion tokens.'
heading = 'Poter Token Economy Model'
[params.whatsnew.button]
hero_class = 'mid-2'
text = 'REad More'
url = '/blog/poters-token-economy-model/'

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
no = 'Sorry to hear that. Please <a href="https://github.com/potercoin/potercoin/issues/new">tell us how we can improve</a>.'
yes = 'Glad to hear it! Please <a href="https://github.com/potercoin/potercoin/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
desc = "Follow us on Twitter to get the latest news!"
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/potercoin"
[[params.links.user]]
desc = "Chat with other project users in #users"
icon = "fab fa-telegram"
name = "Telegram"
url = "https://t.me/POTERCHATEN"
[[params.links.user]]
desc = "Development takes place here!"
icon = "fab fa-facebook"
name = "Facebook"
url = "https://facebook.com/PoterCoin"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[menu]
[[menu.main]]
name = "Docs"
url = "/docs/"
pre = "<i class='fas fa-book'></i>"
weight = 10
[[menu.main]]
name = "Blog"
url = "/blog/"
pre = "<i class='fas fa-blog'></i>"
weight = 11
[[menu.main]]
name = "Versions"
url = "/versions/"
pre = "<i class='fas fa-box-open'></i>"
weight = 12

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
